version: '3.9'
services:
  db:
    image: postgres:16-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-codex}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-codexpass}
      POSTGRES_DB: ${POSTGRES_DB:-codexmundi}
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  minio:
    image: quay.io/minio/minio:RELEASE.2024-08-03T04-33-23Z
    restart: unless-stopped
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER:-minioadmin}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD:-minioadmin}
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data

  api:
    build:
      context: ../api
    depends_on:
      - db
      - minio
    env_file:
      - ../.env
    ports:
      - "3000:3000"
    volumes:
      - ../api:/usr/src/app
      - /usr/src/app/node_modules
    command: npm run start:dev

  web:
    build:
      context: ../web
    depends_on:
      - api
    env_file:
      - ../.env
    ports:
      - "5173:5173"
    volumes:
      - ../web:/usr/src/app
      - /usr/src/app/node_modules
    command: npm run dev -- --host

volumes:
  db_data:
  minio_data:
